### PR TITLE
Add operation-times resource, spec and tests

### PR DESCRIPTION
**Pull request by rosogon**
The operation-times is the resource where D.E.R. stores execution times
of every invoked operation on a service instance.

A suggestion of a better name for this resource is appreciated :)

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
Why do you need this information? And can you give me an example of such DER log? Is this a sort of service-instance-report?

**Comment by rosogon** [comment]
@cjdcordeiro : After DER executes an operation on a service, it records the execution time on dataclay. This is needed for SLA. For IT-1, SLA will check that the execution time of a service operation is lower than a threshold. 

It is indexed by (service_instance_id, operation). The operation is the parameter sent to COMPSs, which is something like $class.$methodname

Example:
```
{
  "id": URI,
  "service_instance_id": "service-instance/4517980sdfashjl423167",
  "operation": "eu.mf2c.MyFirstService.matmul",
  "datetime": "2018-04-13T10:00:00.0Z",
  "execution_time": 150.1
}
```

Does it make sense?

**Comment by cjdcordeiro** [comment]
@rosogon , but, if a service instance is the execution of some executable (jar or whatever), will the DER issue multiple operation records for a single service instance?

**Comment by rosogon** [comment]
The service instance is not the execution of an executable, but of a service (in our case, COMPSs), which allows the execution of several methods contained in the jar. 

The flow is sth like:

1.	Use case -> lifecycle.DeployService    # this creates a service instance
2.	Use case -> lifecycle.ExecuteApplication(op1) -> DER.startApplication(op1)
3.	...
4.	Use case -> lifecycle.ExecuteApplication(opn) -> DER.startApplication(opn)
5.	Use case -> lifecycle.TerminateService

It may be the case that the service is create just for one operation, of course. Even in that case, that unique operation can be invoked several times in the same service instance.

**Comment by cjdcordeiro** [comment]
I'm not sure I understand that workflow nor how a regular user/use case would automate the execution of an application...it looks to me that the user would need to maintain some piece of machinery/intelligence outside mf2c in order to make those requests 2-4.

Nevertheless, shall the resource then be named service-instance-operations?

**Comment by rosogon** [comment]
You're right in that the use case have to create the service, make the appropriate calls and terminate the service. 

I would not name it service-instance-operations, because I think that it could be confused with an instance that represents the possible operations a service has, and that is not the case. But probably better than the current name, so I can change it.

**Review by cjdcordeiro — APPROVED** [review]
lgtm. If you don't agree with my renamings please create an issue or another PR

**Pull request merged**
