### PR TITLE
 modified service definition 

### PR DESCRIPTION
**Pull request by fcarp10**

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
what is the meaning of these new attributes?

**Comment by fcarp10** [comment]
> what is the meaning of these new attributes?

Utilization used by Analytics

**Comment by cjdcordeiro** [comment]
but then this is real time usage...shouldn't be in the service definition

**Comment by fcarp10** [comment]
> but then this is real time usage...shouldn't be in the service definition

modified

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
tests are failing:

```
FAIL in (lifecycle) (service_lifecycle_test.clj:123)
Expecting status 201 got 400. Message: resource does not satisfy defined schema:
-- Spec failed --------------------

  {:category ...,
   :agent_type ...,
   :cpu_arch ...,
   :exec ...,
   :updated ...,
   :name ...,
   :created ...,
   :memory_min ...,
   :exec_type ...,
   :opt_resource ...,
   :id ...,
   :acl ...,
   :exec_ports ...,
   :resourceURI ...,
   :os ...,
   :req_resource ...,
   :disk ...,
   ^^^^^
   :storage_min ...}

should be one of: :acl, :agent_type, :category, :cpu_arch, :cpu_recommended, :created, :description, :disk_recommended, :exec, :exec_ports, :exec_type, :id, :memory_recommended, :name, :network_recommended, :num_agents, :operations, :opt_resource, :os, :properties, :req_resource, :resourceURI, :sla_templates, :storage_min, :updated

-- Relevant specs -------

:cimi/service:
  (clojure.spec.alpha/merge
   (clojure.spec.alpha/keys
    :req-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/id
     :com.sixsq.slipstream.ssclj.resources.spec.common/resourceURI
     :com.sixsq.slipstream.ssclj.resources.spec.common/created
     :com.sixsq.slipstream.ssclj.resources.spec.common/updated
     :com.sixsq.slipstream.ssclj.resources.spec.common/acl
     :com.sixsq.slipstream.ssclj.resources.spec.common/name
     :cimi.service/exec
     :cimi.service/exec_type
     :cimi.service/agent_type]
    :opt-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/description
     :com.sixsq.slipstream.ssclj.resources.spec.common/properties
     :com.sixsq.slipstream.ssclj.resources.spec.common/operations
     :cimi.service/sla_templates
     :cimi.service/exec_ports
     :cimi.service/num_agents
     :cimi.service/cpu_arch
     :cimi.service/os
     :cimi.service/cpu_recommended
     :cimi.service/memory_recommended
     :cimi.service/disk_recommended
     :cimi.service/network_recommended
     :cimi.service/storage_min
     :cimi.service/req_resource
     :cimi.service/opt_resource
     :cimi.service/category])
   (clojure.spec.alpha/map-of
    #{:description :properties :category :agent_type :cpu_arch :exec
      :updated :name :created :num_agents :exec_type :opt_resource :id
      :disk_recommended :acl :operations :exec_ports :resourceURI :os
      :req_resource :storage_min :cpu_recommended :memory_recommended
      :sla_templates :network_recommended}
    clojure.core/any?))

-- Spec failed --------------------

  {:category ...,
   :disk ...,
   :agent_type ...,
   :cpu_arch ...,
   :exec ...,
   :updated ...,
   :name ...,
   :created ...,
   :exec_type ...,
   :opt_resource ...,
   :id ...,
   :acl ...,
   :exec_ports ...,
   :resourceURI ...,
   :os ...,
   :req_resource ...,
   :memory_min ...,
   ^^^^^^^^^^^
   :storage_min ...}

should be one of: :acl, :agent_type, :category, :cpu_arch, :cpu_recommended, :created, :description, :disk_recommended, :exec, :exec_ports, :exec_type, :id, :memory_recommended, :name, :network_recommended, :num_agents, :operations, :opt_resource, :os, :properties, :req_resource, :resourceURI, :sla_templates, :storage_min, :updated

-- Relevant specs -------

:cimi/service:
  (clojure.spec.alpha/merge
   (clojure.spec.alpha/keys
    :req-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/id
     :com.sixsq.slipstream.ssclj.resources.spec.common/resourceURI
     :com.sixsq.slipstream.ssclj.resources.spec.common/created
     :com.sixsq.slipstream.ssclj.resources.spec.common/updated
     :com.sixsq.slipstream.ssclj.resources.spec.common/acl
     :com.sixsq.slipstream.ssclj.resources.spec.common/name
     :cimi.service/exec
     :cimi.service/exec_type
     :cimi.service/agent_type]
    :opt-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/description
     :com.sixsq.slipstream.ssclj.resources.spec.common/properties
     :com.sixsq.slipstream.ssclj.resources.spec.common/operations
     :cimi.service/sla_templates
     :cimi.service/exec_ports
     :cimi.service/num_agents
     :cimi.service/cpu_arch
     :cimi.service/os
     :cimi.service/cpu_recommended
     :cimi.service/memory_recommended
     :cimi.service/disk_recommended
     :cimi.service/network_recommended
     :cimi.service/storage_min
     :cimi.service/req_resource
     :cimi.service/opt_resource
     :cimi.service/category])
   (clojure.spec.alpha/map-of
    #{:description :properties :category :agent_type :cpu_arch :exec
      :updated :name :created :num_agents :exec_type :opt_resource :id
      :disk_recommended :acl :operations :exec_ports :resourceURI :os
      :req_resource :storage_min :cpu_recommended :memory_recommended
      :sla_templates :network_recommended}
    clojure.core/any?))

-------------------------
Detected 2 errors

expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 201 400))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (lifecycle_test_utils.clj:177)
Location header missing from response
expected: uri
  actual: nil

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:137)
Expecting status 200 got 404. Message: unknown resource
expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 200 404))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:138)
Missing delete in clojure.lang.LazySeq@1
expected: op__6503__auto__
  actual: nil

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:147)
Expecting status 403 got 404. Message: unknown resource
expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 403 404))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:153)
Expecting status 200 got 404. Message: unknown resource
expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 200 404))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

ERROR in (lifecycle) (Matcher.java:1283)
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.NullPointerException: null
 at java.util.regex.Matcher.getTextLength (Matcher.java:1283)
    java.util.regex.Matcher.reset (Matcher.java:309)
    java.util.regex.Matcher.<init> (Matcher.java:229)
    java.util.regex.Pattern.matcher (Pattern.java:1093)
    java.util.regex.Pattern.split (Pattern.java:1206)
    java.util.regex.Pattern.split (Pattern.java:1273)
    clojure.string$split.invokeStatic (string.clj:224)
    clojure.string$split.invoke (string.clj:219)
    com.sixsq.slipstream.ssclj.resources.common.utils$split_resource_id.invokeStatic (utils.clj:49)
    com.sixsq.slipstream.ssclj.resources.common.utils$split_resource_id.invoke (utils.clj:45)
    com.sixsq.slipstream.ssclj.resources.common.crud$resource_id_dispatch.invokeStatic (crud.clj:21)
    com.sixsq.slipstream.ssclj.resources.common.crud$resource_id_dispatch.doInvoke (crud.clj:19)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    clojure.lang.MultiFn.invoke (MultiFn.java:233)
    com.sixsq.slipstream.ssclj.resources.example_resource.utils$update_callback_state_BANG_.invokeStatic (utils.clj:22)
    com.sixsq.slipstream.ssclj.resources.example_resource.utils$update_callback_state_BANG_.invoke (utils.clj:18)
    clojure.core$partial$fn__5824.invoke (core.clj:2624)
    com.sixsq.slipstream.ssclj.resources.service_lifecycle_test$fn__9317$fn__9320.invoke (service_lifecycle_test.clj:162)
    clojure.core$with_redefs_fn.invokeStatic (core.clj:7514)
    clojure.core$with_redefs_fn.invoke (core.clj:7498)
    com.sixsq.slipstream.ssclj.resources.service_lifecycle_test$fn__9317.invokeStatic (service_lifecycle_test.clj:50)
    com.sixsq.slipstream.ssclj.resources.service_lifecycle_test/fn (service_lifecycle_test.clj:49)
    clojure.test$test_var$fn__9707.invoke (test.clj:717)
    clojure.test$test_var.invokeStatic (test.clj:717)
    clojure.test$test_var.invoke (test.clj:708)
    clojure.test$test_vars$fn__9733$fn__9738.invoke (test.clj:735)
    com.sixsq.slipstream.ssclj.resources.lifecycle_test_utils$with_test_server_fixture.invokeStatic (lifecycle_test_utils.clj:412)
    com.sixsq.slipstream.ssclj.resources.lifecycle_test_utils$with_test_server_fixture.invoke (lifecycle_test_utils.clj:400)
    clojure.test$compose_fixtures$fn__9701$fn__9702.invoke (test.clj:694)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    clojure.test$compose_fixtures$fn__9701.invoke (test.clj:694)
    clojure.test$test_vars$fn__9733.invoke (test.clj:735)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    clojure.test$test_vars.invokeStatic (test.clj:731)
    clojure.test$test_all_vars.invokeStatic (test.clj:737)
    clojure.test$test_ns.invokeStatic (test.clj:758)
    clojure.test$test_ns.invoke (test.clj:743)
    user$eval224$fn__285.invoke (form-init7283131188100431537.clj:1)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.injected$compose_hooks$fn__154.doInvoke (form-init7283131188100431537.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.injected$run_hooks.invokeStatic (form-init7283131188100431537.clj:1)
    leiningen.core.injected$run_hooks.invoke (form-init7283131188100431537.clj:1)
    leiningen.core.injected$prepare_for_hooks$fn__159$fn__160.doInvoke (form-init7283131188100431537.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$map$fn__5851.invoke (core.clj:2755)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:709)
    clojure.core$next__5371.invokeStatic (core.clj:64)
    clojure.core$reduce1.invokeStatic (core.clj:944)
    clojure.core$reduce1.invokeStatic (core.clj:934)
    clojure.core$merge_with.invokeStatic (core.clj:3059)
    clojure.core$merge_with.doInvoke (core.clj:3051)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.test$run_tests.invokeStatic (test.clj:768)
    clojure.test$run_tests.doInvoke (test.clj:768)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    user$eval224$fn__297$fn__330.invoke (form-init7283131188100431537.clj:1)
    user$eval224$fn__297$fn__298.invoke (form-init7283131188100431537.clj:1)
    user$eval224$fn__297.invoke (form-init7283131188100431537.clj:1)
    user$eval224.invokeStatic (form-init7283131188100431537.clj:1)
    user$eval224.invoke (form-init7283131188100431537.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:7176)
    clojure.lang.Compiler.eval (Compiler.java:7166)
    clojure.lang.Compiler.load (Compiler.java:7635)
    clojure.lang.Compiler.loadFile (Compiler.java:7573)
    clojure.main$load_script.invokeStatic (main.clj:452)
    clojure.main$init_opt.invokeStatic (main.clj:454)
    clojure.main$init_opt.invoke (main.clj:454)
    clojure.main$initialize.invokeStatic (main.clj:485)
    clojure.main$null_opt.invokeStatic (main.clj:519)
    clojure.main$null_opt.invoke (main.clj:516)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)```

you can run them by doing using the `sixsq/slipstream:build` container and running mvn inside

**Comment by fcarp10** [comment]
tests updated

**Comment by cjdcordeiro** [comment]
```FAIL in (lifecycle) (service_lifecycle_test.clj:127)
Expecting status 201 got 400. Message: resource does not satisfy defined schema:
-- Spec failed --------------------

  {:category ...,
   :agent_type ...,
   :cpu_arch ...,
   :exec ...,
   :updated ...,
   :name ...,
   :created ...,
   :exec_type ...,
   :opt_resource ...,
   :id ...,
   :disk_recommended "0.0",
                     ^^^^^
   :acl ...,
   :exec_ports ...,
   :resourceURI ...,
   :os ...,
   :req_resource ...,
   :storage_min ...,
   :cpu_recommended ...,
   :memory_recommended ...,
   :network_recommended ...}

should satisfy

  float?

or value

  {:category ...,
   :agent_type ...,
   :cpu_arch ...,
   :exec ...,
   :updated ...,
   :name ...,
   :created ...,
   :exec_type ...,
   :opt_resource ...,
   :id ...,
   :disk_recommended ...,
   :acl ...,
   :exec_ports ...,
   :resourceURI ...,
   :os ...,
   :req_resource ...,
   :storage_min ...,
   :cpu_recommended "0.0",
                    ^^^^^
   :memory_recommended ...,
   :network_recommended ...}

should satisfy

  float?

-- Relevant specs -------

:cimi.service/network_recommended:
  clojure.core/float?
:cimi.service/memory_recommended:
  clojure.core/float?
:cimi.service/cpu_recommended:
  clojure.core/float?
:cimi.service/disk_recommended:
  clojure.core/float?
:cimi/service:
  (clojure.spec.alpha/merge
   (clojure.spec.alpha/keys
    :req-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/id
     :com.sixsq.slipstream.ssclj.resources.spec.common/resourceURI
     :com.sixsq.slipstream.ssclj.resources.spec.common/created
     :com.sixsq.slipstream.ssclj.resources.spec.common/updated
     :com.sixsq.slipstream.ssclj.resources.spec.common/acl
     :com.sixsq.slipstream.ssclj.resources.spec.common/name
     :cimi.service/exec
     :cimi.service/exec_type
     :cimi.service/agent_type]
    :opt-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/description
     :com.sixsq.slipstream.ssclj.resources.spec.common/properties
     :com.sixsq.slipstream.ssclj.resources.spec.common/operations
     :cimi.service/sla_templates
     :cimi.service/exec_ports
     :cimi.service/num_agents
     :cimi.service/cpu_arch
     :cimi.service/os
     :cimi.service/cpu_recommended
     :cimi.service/memory_recommended
     :cimi.service/disk_recommended
     :cimi.service/network_recommended
     :cimi.service/storage_min
     :cimi.service/req_resource
     :cimi.service/opt_resource
     :cimi.service/category])
   (clojure.spec.alpha/map-of
    #{:description :properties :category :agent_type :cpu_arch :exec
      :updated :name :created :num_agents :exec_type :opt_resource :id
      :disk_recommended :acl :operations :exec_ports :resourceURI :os
      :req_resource :storage_min :cpu_recommended :memory_recommended
      :sla_templates :network_recommended}
    clojure.core/any?))

-- Spec failed --------------------

  {:category ...,
   :agent_type ...,
   :cpu_arch ...,
   :exec ...,
   :updated ...,
   :name ...,
   :created ...,
   :exec_type ...,
   :opt_resource ...,
   :id ...,
   :disk_recommended ...,
   :acl ...,
   :exec_ports ...,
   :resourceURI ...,
   :os ...,
   :req_resource ...,
   :storage_min ...,
   :cpu_recommended ...,
   :memory_recommended "0.0",
                       ^^^^^
   :network_recommended ...}

should satisfy

  float?

or value

  {:category ...,
   :agent_type ...,
   :cpu_arch ...,
   :exec ...,
   :updated ...,
   :name ...,
   :created ...,
   :exec_type ...,
   :opt_resource ...,
   :id ...,
   :disk_recommended ...,
   :acl ...,
   :exec_ports ...,
   :resourceURI ...,
   :os ...,
   :req_resource ...,
   :storage_min ...,
   :cpu_recommended ...,
   :memory_recommended ...,
   :network_recommended "0.0"}
                        ^^^^^

should satisfy

  float?

-- Relevant specs -------

:cimi.service/network_recommended:
  clojure.core/float?
:cimi.service/memory_recommended:
  clojure.core/float?
:cimi.service/cpu_recommended:
  clojure.core/float?
:cimi.service/disk_recommended:
  clojure.core/float?
:cimi/service:
  (clojure.spec.alpha/merge
   (clojure.spec.alpha/keys
    :req-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/id
     :com.sixsq.slipstream.ssclj.resources.spec.common/resourceURI
     :com.sixsq.slipstream.ssclj.resources.spec.common/created
     :com.sixsq.slipstream.ssclj.resources.spec.common/updated
     :com.sixsq.slipstream.ssclj.resources.spec.common/acl
     :com.sixsq.slipstream.ssclj.resources.spec.common/name
     :cimi.service/exec
     :cimi.service/exec_type
     :cimi.service/agent_type]
    :opt-un
    [:com.sixsq.slipstream.ssclj.resources.spec.common/description
     :com.sixsq.slipstream.ssclj.resources.spec.common/properties
     :com.sixsq.slipstream.ssclj.resources.spec.common/operations
     :cimi.service/sla_templates
     :cimi.service/exec_ports
     :cimi.service/num_agents
     :cimi.service/cpu_arch
     :cimi.service/os
     :cimi.service/cpu_recommended
     :cimi.service/memory_recommended
     :cimi.service/disk_recommended
     :cimi.service/network_recommended
     :cimi.service/storage_min
     :cimi.service/req_resource
     :cimi.service/opt_resource
     :cimi.service/category])
   (clojure.spec.alpha/map-of
    #{:description :properties :category :agent_type :cpu_arch :exec
      :updated :name :created :num_agents :exec_type :opt_resource :id
      :disk_recommended :acl :operations :exec_ports :resourceURI :os
      :req_resource :storage_min :cpu_recommended :memory_recommended
      :sla_templates :network_recommended}
    clojure.core/any?))

-------------------------
Detected 2 errors

expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 201 400))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (lifecycle_test_utils.clj:177)
Location header missing from response
expected: uri
  actual: nil

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:141)
Expecting status 200 got 404. Message: unknown resource
expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 200 404))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:142)
Missing delete in clojure.lang.LazySeq@1
expected: op__6503__auto__
  actual: nil

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:151)
Expecting status 403 got 404. Message: unknown resource
expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 403 404))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

FAIL in (lifecycle) (service_lifecycle_test.clj:157)
Expecting status 200 got 404. Message: unknown resource
expected: (clojure.core/= status__6461__auto__ actual__6462__auto__)
  actual: (not (clojure.core/= 200 404))

lein test :only com.sixsq.slipstream.ssclj.resources.service-lifecycle-test/lifecycle

ERROR in (lifecycle) (Matcher.java:1283)
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.NullPointerException: null
 at java.util.regex.Matcher.getTextLength (Matcher.java:1283)
    java.util.regex.Matcher.reset (Matcher.java:309)
    java.util.regex.Matcher.<init> (Matcher.java:229)
    java.util.regex.Pattern.matcher (Pattern.java:1093)
    java.util.regex.Pattern.split (Pattern.java:1206)
    java.util.regex.Pattern.split (Pattern.java:1273)
    clojure.string$split.invokeStatic (string.clj:224)
    clojure.string$split.invoke (string.clj:219)
    com.sixsq.slipstream.ssclj.resources.common.utils$split_resource_id.invokeStatic (utils.clj:49)
    com.sixsq.slipstream.ssclj.resources.common.utils$split_resource_id.invoke (utils.clj:45)
    com.sixsq.slipstream.ssclj.resources.common.crud$resource_id_dispatch.invokeStatic (crud.clj:21)
    com.sixsq.slipstream.ssclj.resources.common.crud$resource_id_dispatch.doInvoke (crud.clj:19)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    clojure.lang.MultiFn.invoke (MultiFn.java:233)
    com.sixsq.slipstream.ssclj.resources.example_resource.utils$update_callback_state_BANG_.invokeStatic (utils.clj:22)
    com.sixsq.slipstream.ssclj.resources.example_resource.utils$update_callback_state_BANG_.invoke (utils.clj:18)
    clojure.core$partial$fn__5824.invoke (core.clj:2624)
    com.sixsq.slipstream.ssclj.resources.service_lifecycle_test$fn__9317$fn__9320.invoke (service_lifecycle_test.clj:166)
    clojure.core$with_redefs_fn.invokeStatic (core.clj:7514)
    clojure.core$with_redefs_fn.invoke (core.clj:7498)
    com.sixsq.slipstream.ssclj.resources.service_lifecycle_test$fn__9317.invokeStatic (service_lifecycle_test.clj:50)
    com.sixsq.slipstream.ssclj.resources.service_lifecycle_test/fn (service_lifecycle_test.clj:49)
    clojure.test$test_var$fn__9707.invoke (test.clj:717)
    clojure.test$test_var.invokeStatic (test.clj:717)
    clojure.test$test_var.invoke (test.clj:708)
    clojure.test$test_vars$fn__9733$fn__9738.invoke (test.clj:735)
    com.sixsq.slipstream.ssclj.resources.lifecycle_test_utils$with_test_server_fixture.invokeStatic (lifecycle_test_utils.clj:412)
    com.sixsq.slipstream.ssclj.resources.lifecycle_test_utils$with_test_server_fixture.invoke (lifecycle_test_utils.clj:400)
    clojure.test$compose_fixtures$fn__9701$fn__9702.invoke (test.clj:694)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    clojure.test$compose_fixtures$fn__9701.invoke (test.clj:694)
    clojure.test$test_vars$fn__9733.invoke (test.clj:735)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    clojure.test$test_vars.invokeStatic (test.clj:731)
    clojure.test$test_all_vars.invokeStatic (test.clj:737)
    clojure.test$test_ns.invokeStatic (test.clj:758)
    clojure.test$test_ns.invoke (test.clj:743)
    user$eval224$fn__285.invoke (form-init2792444064685999118.clj:1)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.injected$compose_hooks$fn__154.doInvoke (form-init2792444064685999118.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.injected$run_hooks.invokeStatic (form-init2792444064685999118.clj:1)
    leiningen.core.injected$run_hooks.invoke (form-init2792444064685999118.clj:1)
    leiningen.core.injected$prepare_for_hooks$fn__159$fn__160.doInvoke (form-init2792444064685999118.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$map$fn__5851.invoke (core.clj:2755)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:709)
    clojure.core$next__5371.invokeStatic (core.clj:64)
    clojure.core$reduce1.invokeStatic (core.clj:944)
    clojure.core$reduce1.invokeStatic (core.clj:934)
    clojure.core$merge_with.invokeStatic (core.clj:3059)
    clojure.core$merge_with.doInvoke (core.clj:3051)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.test$run_tests.invokeStatic (test.clj:768)
    clojure.test$run_tests.doInvoke (test.clj:768)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    user$eval224$fn__297$fn__330.invoke (form-init2792444064685999118.clj:1)
    user$eval224$fn__297$fn__298.invoke (form-init2792444064685999118.clj:1)
    user$eval224$fn__297.invoke (form-init2792444064685999118.clj:1)
    user$eval224.invokeStatic (form-init2792444064685999118.clj:1)
    user$eval224.invoke (form-init2792444064685999118.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:7176)
    clojure.lang.Compiler.eval (Compiler.java:7166)
    clojure.lang.Compiler.load (Compiler.java:7635)
    clojure.lang.Compiler.loadFile (Compiler.java:7573)
    clojure.main$load_script.invokeStatic (main.clj:452)
    clojure.main$init_opt.invokeStatic (main.clj:454)
    clojure.main$init_opt.invoke (main.clj:454)
    clojure.main$initialize.invokeStatic (main.clj:485)
    clojure.main$null_opt.invokeStatic (main.clj:519)
    clojure.main$null_opt.invoke (main.clj:516)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)```

**Review by cjdcordeiro — APPROVED** [review]

**Pull request merged**
