### PR TITLE
Update the `device` and `device-dynamic`

### PR DESCRIPTION
**Pull request by ssgUPC**
Updated the `device` and `device-dynamic`, also added the `actuatorInfo` and `powerPlugged` into the `device-dynamic`

### CODE REVIEW

**Comment by ssgUPC** [comment]
@cjdcordeiro @sstanovnik I have already updated the CIMI resources and also modified my code. The latest `docker-image` of the `resource-categorization` is `latest-V2.0.8`....so you can start testing with that.

**Comment by sstanovnik** [comment]
@ssgUPC this might be slightly off-topic in this PR, but do you have any documentation on how to use resource categorisation? I can't seem to find any code on github. 

I've looked at what's in the docker image and I assume I need to POSt to the categorizer directly on `/api/v1/resource-management/categorization/sensors` in order to set sensor information, which will then get pushed to dataclay, and thus be available in CIMI, right? I also assume the format is identical to the one in device-dynamic.

**Comment by cjdcordeiro** [comment]
>  I assume I need to POSt to the categorizer directly on /api/v1/resource-management/categorization/sensors

I hope not. If you need to edit the device-dynamic, can't you talk with cimi?

**Comment by sstanovnik** [comment]
The categorisation does talk with CIMI, this is only to enable end-to-end testing: because the categorisation can't identify sensors yet, I need a way to force set them, thus that specific call. I just need a step up from mocking my device-dynamic calls.

**Comment by cjdcordeiro** [comment]
sure, so you can just ask cimi to edit them...why do we need yet another proxy? If your data is not going to be processed, just proxied, then speak with CIMI

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
tests are failing

```

FAIL in (check-device-resource-schema) (device_dynamic_test.cljc:45)
expected: (s/valid? :cimi/device-dynamic device-dynamic-resource)
  actual: (not (s/valid? :cimi/device-dynamic {:wifiAddress "[snic(family=<AddressFamily.AF_INET: 2>, address='10.192.167.20', netmask='255.255.0.0', broadcast='10.192.255.255', ptp=None), snic(family=<AddressFamily.AF_INET6: 10>, address='fe80::fe39:ed60:dff6:db85%wlp3s0', netmask='ffff:ffff:ffff:ffff::', broadcast=None, ptp=None), snic(family=<AddressFamily.AF_PACKET: 17>, address='d4:6a:6a:9a:6b:87', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)]", :ramFree 5225.359375, :ethernetAddress "[snic(family=<AddressFamily.AF_PACKET: 17>, address='50:9a:4c:cf:f4:b9', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)]", :updated "1964-08-25T10:00:00.0Z", :created "1964-08-25T10:00:00.0Z", :sensors [{:sensorType "mytype", :sensorModel "mymodel", :sensorConnection "myconn"}], :storageFreePercent 95.1, :wifiThroughputInfo ["21689997" "950419307" "150482" "663270" "0" "0" "0" "0"], :myLeaderID {:href "device/889345efdet"}, :id "device-dynamic/device-dynamic-resource", :ethernetThroughputInfo ["0" "0" "0" "0" "0" "0" "0" "0"], :powerRemainingStatus "97.42316050915865", :cpuFreePercent 50.4, :acl {:owner {:principal "ADMIN", :type "ROLE"}, :rules [{:principal "ADMIN", :type "ROLE", :right "MODIFY"}]}, :resourceURI "http://schemas.dmtf.org/cimi/2/DeviceDynamic", :device {:href "device/142165441eewe"}, :ramFreePercent 66.4, :powerRemainingStatusSeconds "10557", :storageFree 211712.4765625}))```

**Comment by sstanovnik** [comment]
It's only because I'd like to use the categorisation module. A "better" way might be to use environment variables to mock what sensors are recognised, but it's an HTTP endpoint instead. 

@ssgUPC an environment variable would be nice, and it would lend itself well to being used in the agent setup script/dcompose files. I'd open an issue in the categorisation repository, but there doesn't seem to be one here.

**Comment by ssgUPC** [comment]
> tests are failing
> 
> ```
> 
> FAIL in (check-device-resource-schema) (device_dynamic_test.cljc:45)
> expected: (s/valid? :cimi/device-dynamic device-dynamic-resource)
>   actual: (not (s/valid? :cimi/device-dynamic {:wifiAddress "[snic(family=<AddressFamily.AF_INET: 2>, address='10.192.167.20', netmask='255.255.0.0', broadcast='10.192.255.255', ptp=None), snic(family=<AddressFamily.AF_INET6: 10>, address='fe80::fe39:ed60:dff6:db85%wlp3s0', netmask='ffff:ffff:ffff:ffff::', broadcast=None, ptp=None), snic(family=<AddressFamily.AF_PACKET: 17>, address='d4:6a:6a:9a:6b:87', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)]", :ramFree 5225.359375, :ethernetAddress "[snic(family=<AddressFamily.AF_PACKET: 17>, address='50:9a:4c:cf:f4:b9', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)]", :updated "1964-08-25T10:00:00.0Z", :created "1964-08-25T10:00:00.0Z", :sensors [{:sensorType "mytype", :sensorModel "mymodel", :sensorConnection "myconn"}], :storageFreePercent 95.1, :wifiThroughputInfo ["21689997" "950419307" "150482" "663270" "0" "0" "0" "0"], :myLeaderID {:href "device/889345efdet"}, :id "device-dynamic/device-dynamic-resource", :ethernetThroughputInfo ["0" "0" "0" "0" "0" "0" "0" "0"], :powerRemainingStatus "97.42316050915865", :cpuFreePercent 50.4, :acl {:owner {:principal "ADMIN", :type "ROLE"}, :rules [{:principal "ADMIN", :type "ROLE", :right "MODIFY"}]}, :resourceURI "http://schemas.dmtf.org/cimi/2/DeviceDynamic", :device {:href "device/142165441eewe"}, :ramFreePercent 66.4, :powerRemainingStatusSeconds "10557", :storageFree 211712.4765625}))```
> ```

Dear, is there still missing anything in the `device-dynamic` actually, I also added the `actuatorInfo` and `powerPlugged` in the `device-dynamic`. But sorry to say that dear, I don't understand why it is failing

**Comment by ssgUPC** [comment]
> It's only because I'd like to use the categorisation module. A "better" way might be to use environment variables to mock what sensors are recognised, but it's an HTTP endpoint instead.
> 
> @ssgUPC an environment variable would be nice, and it would lend itself well to being used in the agent setup script/dcompose files. I'd open an issue in the categorisation repository, but there doesn't seem to be one here.

@sstanovnik thanks for your suggestion dear, let me think about it once because still, I don't know how to pass the `sensor` information to my categorization module...you remember during the last conversation, I asked you about the way of having `sensor metadata`...so, I thought that I need to provide with sketch, which could be executed on Arduino...in order to just pass the `sensor information` ....that's why I opened an URL...but dear, please let me think about it once....

**Review by ssgUPC — COMMENTED** [review]
Modified the CIMI resource schema for `device` and `device-dynamic`

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
it's still failing. please compile it in your machine to see what the error is

**Comment by ssgUPC** [comment]
> it's still failing. please compile it in your machine to see what the error is

Just one question the error is coming from the `device-dynamic` or `device` schema?

**Review by cjdcordeiro — APPROVED** [review]

**Pull request merged**
