### PR TITLE
Added the `status` info into `device` 

### PR DESCRIPTION
**Pull request by ssgUPC**
@cjdcordeiro I have already tested the CIMI locally and added the `status` info to the `device`

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
@ssgUPC is this still valid?

**Comment by ssgUPC** [comment]
yes it is valid but before you release the new version of `CIMI` please let me know that actually I also need to upload new `docker-image`

**Comment by cjdcordeiro** [comment]
once you upload the new image let me know

**Comment by ssgUPC** [comment]
Uploading the new image

**Pull request merged**
