### PR TITLE
Add template resource and tests

### PR DESCRIPTION
**Pull request by rosogon**
The documentation is now in the readthedocs, isn't it? If not, let me know where in the project and I will add it for templates.

### CODE REVIEW

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
lgtm but it should not be named template.

that's too generic and prone to misinterpretation since all cimi resources can be templated

**Comment by rosogon** [comment]
sla-template?

**Comment by cjdcordeiro** [comment]
can be

**Review by cjdcordeiro — APPROVED** [review]
lgtm

**Pull request merged**
